### ISSUE TITLE
How to import the componets unless the global mode

### ISSUE THREAD

**Issue by logofun** [alvinindra/vue3-quilljs#1]
Hi, from the code, I notice that this component was used by Global Registration:
```js
// vue - main.js
import Quill from 'vue3-quilljs'
import 'vue3-quilljs/lib/style.css'
app.use(Quill)`
```
now I want to import the `richTextEditor` in the vue componet and template, just like the below code:
```js
import {richTextEditor} from 'vue3-quilljs'
```

**Comment by alvinindra** [comment]
You can do this to register in component
```vue
<script setup lang="ts">
import { ref } from 'vue'
import { richTextEditor } from 'vue3-quilljs'
import 'vue3-quilljs/lib/style.css'

const toolBarConfig = [
  [{ header: [1, 2, 3, false] }],
  [{ color: [] }, { background: [] }],
  ['bold', 'italic', 'underline', 'strike'],
  [{ align: [] }],
  ['clean']
]
const rawHTML = ref('')
</script>

<template>
  <richTextEditor
    :toolBarConfig="toolBarConfig"
    placeholder="Write a text"
    v-model="rawHTML"
    theme="snow"
  ></richTextEditor>
</template>
```

**Comment by logofun** [comment]
![image](https://user-images.githubusercontent.com/22115036/153702463-b4d7b3ec-5c6d-4c60-be8e-39a7a8c8f572.png)
 It seems that no useful.
`Module '"vue3-quilljs"' has no exported member 'richTextEditor'.Vetur(2305)`

**Comment by alvinindra** [comment]
Maybe it will be better to change the package to this https://vueup.github.io/vue-quill/  than my package.

**Comment by logofun** [comment]
thanks for your respond.
